"""Final assembly: stitch 8 clips, mix audio, burn captions, export 1080x1920 mp4.

Pipeline (single ffmpeg invocation where possible):
1. Concat 8 video clips (with their native dialogue audio).
2. Pad/scale each to 1080x1920 in case Veo returned a slightly different size.
3. Mix the dialogue against the background music with sidechain ducking
   (music auto-dips when dialogue plays).
4. Burn the ASS subtitle file generated by captions.py.
5. Encode H.264, yuv420p, AAC.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from . import captions

DIALOGUE_GAIN_DB = 5      # boost the Veo audio
MUSIC_GAIN_DB = -20       # quiet the background song
DUCK_THRESHOLD = 0.05     # sidechain trigger
TARGET_W, TARGET_H = 1080, 1920
TARGET_FPS = 30
CROSSFADE_SECONDS = 0.0   # set > 0 for crossfade; 0 = hard cuts (faster, fewer artifacts)


def _ffmpeg() -> str:
    exe = shutil.which("ffmpeg")
    if not exe:
        raise RuntimeError("ffmpeg not found on PATH. Install with `winget install ffmpeg`.")
    return exe


def _ass_path_for_filter(p: Path) -> str:
    """ffmpeg's `subtitles` filter is fussy about Windows paths and colons."""
    s = str(p.resolve()).replace("\\", "/").replace(":", "\\:")
    return s


def _build_concat_filter(num_clips: int) -> str:
    """Scale + pad each clip to 1080x1920, then concat video+audio."""
    parts = []
    for i in range(num_clips):
        parts.append(
            f"[{i}:v]scale={TARGET_W}:{TARGET_H}:force_original_aspect_ratio=decrease,"
            f"pad={TARGET_W}:{TARGET_H}:(ow-iw)/2:(oh-ih)/2,"
            f"setsar=1,fps={TARGET_FPS}[v{i}];"
            f"[{i}:a]aresample=44100[a{i}];"
        )
    concat_inputs = "".join(f"[v{i}][a{i}]" for i in range(num_clips))
    parts.append(f"{concat_inputs}concat=n={num_clips}:v=1:a=1[vcat][acat];")
    return "".join(parts)


def _build_audio_mix(num_clips: int, has_music: bool) -> str:
    """Boost dialogue, attenuate music, sidechain-duck music under dialogue."""
    if not has_music:
        return f"[acat]volume={DIALOGUE_GAIN_DB}dB[aout];"
    music_idx = num_clips  # music is the last input
    return (
        f"[acat]volume={DIALOGUE_GAIN_DB}dB,asplit=2[adial][asc];"
        f"[{music_idx}:a]volume={MUSIC_GAIN_DB}dB[amus];"
        f"[amus][asc]sidechaincompress=threshold={DUCK_THRESHOLD}:ratio=8:attack=5:release=300[aducked];"
        f"[adial][aducked]amix=inputs=2:duration=first:dropout_transition=0[aout];"
    )


def assemble(
    scene_videos: list[Path],
    output_path: Path,
    music_path: Path | None = None,
    subtitle_path: Path | None = None,
) -> Path:
    """Stitch N clips into output_path (N is whatever's passed). Returns output_path."""
    if len(scene_videos) < 2:
        raise ValueError(f"Need at least 2 clips, got {len(scene_videos)}")
    for p in scene_videos:
        if not p.exists():
            raise FileNotFoundError(p)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    cmd: list[str] = [_ffmpeg(), "-y"]
    for v in scene_videos:
        cmd += ["-i", str(v)]
    if music_path:
        cmd += ["-stream_loop", "-1", "-i", str(music_path)]

    filter_graph = _build_concat_filter(len(scene_videos))
    filter_graph += _build_audio_mix(len(scene_videos), has_music=music_path is not None)

    video_label = "[vcat]"
    if subtitle_path:
        filter_graph += f"{video_label}subtitles='{_ass_path_for_filter(subtitle_path)}'[vout];"
        video_label = "[vout]"
    else:
        filter_graph += f"{video_label}null[vout];"
        video_label = "[vout]"

    cmd += [
        "-filter_complex", filter_graph,
        "-map", video_label, "-map", "[aout]",
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "192k",
        "-shortest",
        "-movflags", "+faststart",
        str(output_path),
    ]

    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(
            f"ffmpeg failed (exit {proc.returncode}):\n{proc.stderr[-2000:]}"
        )
    return output_path


def assemble_with_captions(
    scene_videos: list[Path],
    project_path: Path,
    music_path: Path | None = None,
) -> Path:
    """Two-pass: 1) concat without subs to get clean audio, 2) transcribe, 3) reassemble with burned subs."""
    rough = project_path / "_rough.mp4"
    assemble(scene_videos, rough, music_path=None, subtitle_path=None)
    ass_path = project_path / "captions.ass"
    captions.generate_subtitles(rough, ass_path)
    final = project_path / "final.mp4"
    assemble(scene_videos, final, music_path=music_path, subtitle_path=ass_path)
    rough.unlink(missing_ok=True)
    return final
